height: 500
menubar: false
toolbar:
  - undo redo | blocks | bold italic | alignleft aligncenter alignright | bullist numlist outdent indent | removeformat | help | link image | 
plugins:
  - insertdatetime lists media table code help wordcount "link image code" emoticons link list table
